name: "Archive Logs and Results"
description: "Capture Docker Compose logs, test reports, and coverage"
inputs:
  reports:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Dump Docker Compose Logs
      run: docker compose logs > docker-compose.log
      if: always()
      shell: bash

    - name: Archive docker-compose logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-compose-logs
        path: docker-compose.log

    - name: Archive spec reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rubocop-reports
        path: ${{ inputs.reports }}

    - name: Upload SimpleCov Coverage JSON
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-${{ env.CI_NODE_INDEX || '0' }}
        path: coverage/.resultset.json
