name: "Archive Logs and Results"
description: "Capture Docker Compose logs and test result artifacts"

inputs:
  reports:
    description: "Path or glob to spec report files to upload"
    required: true

runs:
  using: "composite"
  steps:
    - name: Dump Docker Compose Logs (gracefully)
      run: |
        LOGFILE=docker-compose.log
        : > "$LOGFILE"
        for c in $(docker ps --format '{{.Names}}'); do
          echo "==== Logs for $c ====" >> "$LOGFILE"
          if ! docker logs "$c" >> "$LOGFILE" 2>&1; then
            echo "[WARN] Could not retrieve logs for $c" >> "$LOGFILE"
          fi
          echo "" >> "$LOGFILE"
        done
      if: always()
      shell: bash

    - name: Archive Docker Compose Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-compose-logs-${{ matrix.ci_node_index }}
        path: docker-compose.log

    - name: Archive Spec Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: spec-reports-${{ matrix.ci_node_index }}
        path: ${{ inputs.reports }}

    - name: Archive SimpleCov results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simplecov-coverage-${{ env.CI_NODE_INDEX || '0' }}
        path: tmp/coverage/${{ env.CI_NODE_INDEX }}/.resultset.json
        include-hidden-files: true
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
