name: "Archive Logs and Results"
description: "Capture Docker Compose logs, test reports, and coverage"
inputs:
  reports:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Dump Docker Compose Logs
      run: docker compose logs > docker-compose.log
      if: always()
      shell: bash

    - name: Archive docker-compose logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-compose-logs-${{ env.CI_NODE_INDEX || '0' }}
        path: docker-compose.log

    - name: Archive spec reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: rubocop-reports-${{ env.CI_NODE_INDEX || '0' }}
        path: ${{ inputs.reports }}

    - name: Archive SimpleCov results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: simplecov-coverage-${{ env.CI_NODE_INDEX || '0' }}
        path: tmp/coverage/${{ env.CI_NODE_INDEX }}/.resultset.json
        include-hidden-files: true
        if-no-files-found: warn
        compression-level: 6
        overwrite: true
