name: "Archive Logs and Results"
description: "Capture Docker Compose logs and test result artifacts"

inputs:
  name:
    description: "Name of the artifact"
    required: false
  reports:
    description: "Path or glob to spec report files to upload"
    required: true

runs:
  using: "composite"
  steps:
    - name: Dump Docker Compose Logs (gracefully)
      run: docker compose ps --format "{{.Service}}" -a  | xargs -t -I {} sh -c 'docker compose logs {} >> docker-compose-{}.log'
      if: always()
      shell: bash
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true

    - name: Zip Docker Compose Logs
      run: zip docker-compose.logs.zip docker-compose-*.log
      if: always()
      shell: bash

    - name: Archive Docker Compose Logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: docker-compose-logs-${{ inputs.name || 'unknown' }}
        path: docker-compose.logs.zip

    - name: Archive Spec Reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: spec-reports-${{ matrix.ci_node_index || '0' }}
        path: ${{ inputs.reports }}
