name: "Set up env vars"
description: "Set up env vars"
inputs:
  tag:
    required: false
    type: string
  image_name:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8};
        echo "export DOCKER_CLIENT_TIMEOUT=360";
        echo "export COMPOSE_HTTP_TIMEOUT=360"
    - name: Sanitize repo slug
      env:
        REPO: "${{ inputs.image_name || github.repository }}"
      uses: actions/github-script@v6
      id: repo_slug
      with:
        result-encoding: string
        script: return 'ghcr.io/${{ REPO }}'.toLowerCase()
