name: "Set up env vars"
description: "Set up env vars"
inputs:
  image_name:
    required: false
    type: string
  subdir:
    default: "."
    type: string
  tag:
    required: false
    type: string
  token:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Determine git sha to checkout
      uses: haya14busa/action-cond@v1
      id: gitsha
      with:
        cond: ${{ github.event_name == 'pull_request' }}
        if_true: ${{ github.event.pull_request.head.sha }}
        if_false: ${{ github.sha }}
    - name: Set env
      run: echo "TAG=${GIT_SHA::8}" >> $GITHUB_ENV
      env:
        GIT_SHA: ${{ steps.gitsha.outputs.value }}
      shell: bash
    - name: Downcase repo
      env:
        REPO: "${{ inputs.image_name || github.repository }}"
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
        token: ${{ inputs.token }}
        clean: false
    - name: Make sure env files are present if missing
      run: >-
        cd ${{ inputs.subdir }};
        touch .env.development;
        touch .env;
      shell: bash
    - name: Create more disk space # See https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
      if: ${{ github.job != 'deployment' }}
      run: sudo rm -rf /usr/share/dotnet && sudo rm -rf /opt/ghc && sudo rm -rf "/usr/local/share/boost" && sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      shell: bash
