name: "Set up env vars"
description: "Set up env vars"
inputs:
  tag:
    required: false
    type: string
  image_name:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
    - name: Downcase repo
      env:
        REPO: "${{ inputs.image_name || github.repository }}"
      shell: bash
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}