name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      subdir:
        default: '.'
        type: string
      solr:
        description: "Use if you need to build a specific Solr image and push to the registry"
        required: false
        type: boolean
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string
  workflow_call:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      subdir:
        default: '.'
        type: string
      solr:
        description: "Use if you need to build a specific Solr image and push to the registry"
        required: false
        type: boolean
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: macos-11
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@main
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Retag action for web
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw
            value=latest
            enable={{is_default_branch}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: |
            type=registry
            ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          context: .
          labels: ${{ steps.meta-web.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta-web.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          target: hyku-base
