name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string
  workflow_call:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v0.0.22
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Retag action for base
        if: ${{ inputs.baseTarget != '' }}
        id: meta-base
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for web
        if: ${{ inputs.webTarget != '' }}
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.workerTarget != '' }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solrTarget != '' }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push base
        if: ${{ inputs.baseTarget != '' }}
        uses: scientist-softserv/actions/build-and-push@v0.0.22
        with:
          type: base
          location: /base
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}
      - name: Build and push web
        if: ${{ inputs.webTarget != '' }}
        uses: scientist-softserv/actions/build-and-push@v0.0.22
        with:
          type: web
          location: ""
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}
      - name: Build and push worker
        if: ${{ inputs.workerTarget != '' }}
        uses: scientist-softserv/actions/build-and-push@v0.0.22
        with:
          type: worker
          location: /worker
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-worker.outputs.tags }}
      - name: Build and push solr
        if: ${{ inputs.solrTarget != '' }}
        uses: scientist-softserv/actions/build-and-push@v0.0.22
        with:
          type: solr
          location: /solr
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-solr.outputs.tags }}
