name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string
  workflow_call:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v0.0.14
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up web build
        if: ${{ inputs.webTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Retag action for base
        if: ${{ inputs.baseTarget != '' }}
        id: meta-base
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for web
        if: ${{ inputs.webTarget != '' }}
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.workerTarget != '' }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solrTarget != '' }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push base
        if: ${{ inputs.baseTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base:latest
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-base.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base:${{ env.TAG }}
          target: ${{ inputs.webTarget }}
      - name: Build and push web
        if: ${{ inputs.webTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:latest
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-web.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          target: ${{ inputs.webTarget }}
      - name: Build and push worker
        if: ${{ inputs.workerTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:latest
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-worker.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          target: ${{ inputs.workerTarget }}
      - name: Build and push solr
        if: ${{ inputs.solrTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:latest
          context: ./solr
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-solr.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          target: ${{ inputs.solrTarget }}
