name: "Build Docker Images"
on:
  workflow_dispatch:
  workflow_call:

env:
  REGISTRY: ghcr.io

jobs:
  build:
<<<<<<< Updated upstream
    runs-on: self-hosted
=======
    runs-on: ubuntu-latest
>>>>>>> Stashed changes
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/build-lint-test-action/setup-env@env-test
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
<<<<<<< Updated upstream
        id: builder
        with:
          version: latest
          endpoint: builders
      - name: Append ARM buildx builder
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: "ssh://ec2-user@10.0.6.48"
          ssh_private_key: ${{ secrets.SSH_BESTIE_BUILDER_PRIVATE_KEY }}
      - name: Pull from cache to speed up build
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Retag action for web
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.worker }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solr }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to GitHub Container Registry
=======
      - name: Github Container Login
>>>>>>> Stashed changes
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          touch .env.development;
          TAG=latest docker-compose pull web || true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
<<<<<<< Updated upstream
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
=======
>>>>>>> Stashed changes
          context: .
          platforms: linux/amd64,linux/arm64
          target: hyku-base
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
<<<<<<< Updated upstream
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
=======
>>>>>>> Stashed changes
          context: .
          platforms: linux/amd64,linux/arm64
          target: hyku-worker
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
<<<<<<< Updated upstream
          target: ${{ inputs.workerTarget }}
      - name: Build and push solr
        if: ${{ inputs.solr }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          context: .
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-solr.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          target: ${{ inputs.target }}
=======
>>>>>>> Stashed changes
