name: "Build Docker Images"
on:
  workflow_call:
    inputs:
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@main
        with:
          tag: ${{ inputs.tag }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          target: ${{ inputs.target }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          target: ${{ inputs.workerTarget }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
        if: ${{ inputs.worker }}
