name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string
      use_local_actions:
        description: "When true, use local actions instead of external ones."
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      image_name:
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
        type: string
      platforms:
        default: "linux/amd64,linux/arm64"
        description: "Which platforms you would like built through CI"
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string
      use_local_actions:
        description: "When true, use local actions to ensure correct PR checkout logic."
        required: false
        type: boolean
        default: false

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # This step runs if the flag is FALSE or not provided
      - name: Setup (External)
        id: setup-external
        if: ${{ !inputs.use_local_actions }}
        uses: scientist-softserv/actions/setup-env@v0.0.23
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}

      # This step runs if the flag is TRUE
      - name: Setup (Local)
        id: setup-local
        if: ${{ inputs.use_local_actions }}
        uses: ./setup-env # Use the local, corrected action
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_step == 'build' }}
        with:
          limit-access-to-actor: true
      - name: Retag action for base
        if: ${{ inputs.baseTarget != '' }}
        id: meta-base
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for web
        if: ${{ inputs.webTarget != '' }}
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.workerTarget != '' }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solrTarget != '' }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      # Build and push steps now need the flag check
      - name: Build and push base (External Action)
        if: ${{ inputs.baseTarget != '' && !inputs.use_local_actions }}
        uses: scientist-softserv/actions/build-and-push@v0.0.23
        with:
          type: base
          location: /base
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}
      - name: Build and push base (Local Action)
        if: ${{ inputs.baseTarget != '' && inputs.use_local_actions }}
        uses: ./build-and-push
        with:
          type: base
          location: /base
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}

      - name: Build and push web and worker (External Action)
        if: ${{ inputs.webTarget != '' && inputs.workerTarget != '' && !inputs.use_local_actions }}
        uses: scientist-softserv/actions/build-and-push@v0.0.23
        with:
          type: web,worker
          location: ""
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}
      - name: Build and push web and worker (Local Action)
        if: ${{ inputs.webTarget != '' && inputs.workerTarget != '' && inputs.use_local_actions }}
        uses: ./build-and-push
        with:
          type: web,worker
          location: ""
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}

      - name: Build and push web (External Action)
        if: ${{ inputs.webTarget != '' && inputs.workerTarget == '' && !inputs.use_local_actions }}
        uses: scientist-softserv/actions/build-and-push@v0.0.23
        with:
          type: web
          location: ""
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}
      - name: Build and push web (Local Action)
        if: ${{ inputs.webTarget != '' && inputs.workerTarget == '' && inputs.use_local_actions }}
        uses: ./build-and-push
        with:
          type: web
          location: ""
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-base.outputs.tags }}

      - name: Build and push worker (External Action)
        if: ${{ inputs.workerTarget != '' && inputs.webTarget == '' && !inputs.use_local_actions }}
        uses: scientist-softserv/actions/build-and-push@v0.0.23
        with:
          type: worker
          location: /worker
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-worker.outputs.tags }}
      - name: Build and push worker (Local Action)
        if: ${{ inputs.workerTarget != '' && inputs.webTarget == '' && inputs.use_local_actions }}
        uses: ./build-and-push
        with:
          type: worker
          location: /worker
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-worker.outputs.tags }}

      - name: Build and push solr (External Action)
        if: ${{ inputs.solrTarget != '' && !inputs.use_local_actions }}
        uses: scientist-softserv/actions/build-and-push@v0.0.23
        with:
          type: solr
          location: /solr
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-solr.outputs.tags }}
      - name: Build and push solr (Local Action)
        if: ${{ inputs.solrTarget != '' && inputs.use_local_actions }}
        uses: ./build-and-push
        with:
          type: solr
          location: /solr
          subdir: ${{ inputs.subdir }}
          tags: ${{ steps.meta-solr.outputs.tags }}