name: "Bundler Audit"
run-name: Bundler Audit (${{ github.ref_name }} -> ${{ inputs.environment }}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
  workflow_call:
    inputs:
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v0.0.14
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull web image to prevent build
        if: ${{ inputs.webTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          docker-compose pull web
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Run Bundler Audit
        run: >-
          cd ${{ inputs.subdir }};
          docker-compose run web sh -c "gem install bundler-audit && bundler-audit check --update"
      - name: Publish Bundler Audit Report
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: bundler-audit-report
          path: bundler-audit-report.txt