name: "Bundler Audit"
run-name: Bundler Audit (${{ github.ref_name }}) by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      debug_enabled:
        description: "Enable tmate debug session"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      debug_enabled:
        required: false
        default: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  bundler-audit:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: notch8/actions/setup-env@v1.0.8
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull web image to prevent build
        if: ${{ inputs.webTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          docker compose pull web
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Run Bundler Audit and Copy Report
        run: |
          cd ${{ inputs.subdir }}
          docker compose run --name audit-container web sh -c "gem install bundler-audit && bundler-audit check --update > bundler-audit-report.txt"
          AUDIT_EXIT=$?
          docker cp audit-container:/bundler-audit-report.txt ./bundler-audit-report.txt || true
          docker rm audit-container || true
          exit $AUDIT_EXIT
      - name: Publish Bundler Audit Report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: bundler-audit-report
          path: ${{ inputs.subdir }}/bundler-audit-report.txt