name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      rubocop_cmd:
        default:  bundle exec rubocop --parallel --format progress
        required: false
        type: string
      rubocop_knapsack_cmd:
        default: bundle exec rubocop --parallel --format progress ../
        required: false
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      submoduledir:
        default: 'hyrax-webapp'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string
  workflow_call:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      rubocop_cmd:
        default: bundle exec rubocop --parallel --format progress
        required: false
        type: string
      rubocop_knapsack_cmd:
        default: bundle exec rubocop --parallel --format progress ../
        required: false
        type: string
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: '.'
        type: string
      submoduledir:
        default: 'hyrax-webapp'
        type: string
      tag:
        required: false
        type: string
      webTarget:
        description: "Used to set your target for the web image"
        required: false
        type: string
      workerTarget:
        description: "Used to set your target for the worker image"
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v0.0.17
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Prepare the repository for Hyku Knapsack
        run: |
          git remote add prime https://github.com/samvera-labs/hyku_knapsack
          git fetch prime
          git checkout -b required_for_knapsack_instances --track prime/required_for_knapsack_instances
      - name: Run Rubocop
        run: |
          cd ${{ inputs.subdir }}
          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb
          [ -f "bin/checkout_all.sh" ] && ./bin/checkout_all.sh
          docker compose pull web || true
          docker compose run -T web sh -c "ls -la && pwd && cd ${{ inputs.submoduledir }} && bundle install && bundle exec rubocop --parallel --format progress && bundle exec rubocop --parallel --format progress ../"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
