name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      rubocop_cmd:
        default: bundle exec rubocop --parallel --format progress
        required: false
        type: string
      subdir:
        default: "."
        type: string
      tag:
        required: false
        type: string
  workflow_call:
    inputs:
      rubocop_cmd:
        default: bundle exec rubocop --parallel --format progress --format junit --out rubocop.xml --display-only-failed
        required: false
        type: string
      subdir:
        default: "."
        type: string
      tag:
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: notch8/actions/setup-env@enter_the_matrix
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_step == 'lint' }}
        with:
          limit-access-to-actor: true
      - name: Run Rubocop
        run: >-
          cd ${{ inputs.subdir }};
          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb;
          [ -f "bin/checkout_all.sh" ] && ./bin/checkout_all.sh;
          docker compose pull web || true;
          docker compose run -T web sh -c
          "${{ inputs.rubocop_cmd }}"
      - id: after_care
        name: Upload Logs and Results
        uses: notch8/actions/after-care@enter_the_matrix
        if: always()
        with:
          reports: "rubocop*.xml"
