name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      db:
        default: true
        type: boolean
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      worker:
        required: false
        type: boolean
  workflow_call:
    inputs:
      db:
        default: true
        type: boolean
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      worker:
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@v3plus5
        with:
          tag: ${{ inputs.tag }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to prevent build
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          docker-compose pull web
      - name: Pull worker image to prevent build
        run: >-
          cd ${{ inputs.subdir }};
          docker-compose pull worker
        if: ${{ inputs.worker }}
      - name: Run Rubocop
        run: >-
          cd ${{ inputs.subdir }};
          chmod -f 777 db/schema.rb;
          docker-compose run web bundle exec rubocop --parallel --format progress
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
