name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      lint_cmd:
        required: false
        type: string
        default: docker compose run web bundle exec rubocop --parallel --format progress
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      worker:
        required: false
        type: boolean
  workflow_call:
    inputs:
      lint_cmd:
        required: false
        type: string
        default: docker compose run web bundle exec rubocop --parallel --format progress
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      worker:
        required: false
        type: boolean

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: notch8/actions/setup-env@v0.0.13
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to prevent build
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          docker compose pull web
      - name: Pull worker image to prevent build
        run: >-
          cd ${{ inputs.subdir }};
          docker compose pull worker
        if: ${{ inputs.worker }}
      - name: Run Rubocop
        run: >-
          cd ${{ inputs.subdir }};
          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb;
          [ -f "bin/checkout_all.sh" ] && ./bin/checkout_all.sh;
          ${{ inputs.lint_cmd }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
