name: "Rspec for Rails Apps"
on:
  workflow_dispatch:
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

        # you need TB_RSPEC_OPTIONS: --format RspecJunitFormatter --out rspec.xml and TB_RSPEC_FORMATTER: progress in your .env for this to work
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: '**/r*.xml'
          fail_on_failure: true
          require_passed_tests: true
          detailed_summary: true
