name: "Rspec for Rails Apps"
on:
  workflow_dispatch:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      confdir:
        description: "Solr conf/config directory"
        required: false
        type: string
        default: "/app/samvera/hyrax-webapp/solr/config"
      node_index:
        description: "Node index for Rspec test matrix"
        required: false
        type: string
        default: "[0, 1, 2]"
      node_total:
        description: "Total nodes for Rspec test matrix"
        required: false
        type: string
        default: "[3]"
      rspec_cmd:
        description: "Setup/Run Rspec test(s) command"
        required: false
        type: string
        default: "gem install semaphore_test_boosters && rspec_booster --job ${CI_NODE_INDEX}/${CI_NODE_TOTAL}"
      setup_db_cmd:
        description: "Setup database command"
        required: false
        type: string
        default: "RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate"
      setup_solr_cmd:
        description: "Setup solr command"
        required: false
        type: string
        default: 'solrcloud-upload-configset.sh "${CONFDIR}" && SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh && solrcloud-assign-configset.sh'
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        description: "Used to set your subdirectory"
        default: "."
        type: string
      tag:
        description: "tag"
        required: false
        type: string
  workflow_call:
    inputs:
      baseTarget:
        description: "Used to set your target for the base image"
        required: false
        type: string
      confdir:
        required: false
        type: string
        default: "/app/samvera/hyrax-webapp/solr/config"
      node_index:
        required: false
        type: string
        default: "[0, 1, 2]"
      node_total:
        required: false
        type: string
        default: "[3]"
      rspec_cmd:
        required: false
        type: string
        default: "gem install semaphore_test_boosters && rspec_booster --job ${CI_NODE_INDEX}/${CI_NODE_TOTAL}"
      setup_db_cmd:
        required: false
        type: string
        default: "RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate"
      setup_solr_cmd:
        required: false
        type: string
        default: 'solrcloud-upload-configset.sh "${CONFDIR}" && SOLR_COLLECTION_NAME=hydra-test solrcloud-assign-configset.sh && solrcloud-assign-configset.sh'
      solrTarget:
        description: "Used to set your target for the solr image"
        required: false
        type: string
      subdir:
        default: "."
        type: string
      tag:
        required: false
        type: string

env:
  REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Set N number of parallel jobs you want to run tests on.
        # Use higher number if you have slow tests to split them on more parallel jobs.
        # Remember to update ci_node_index below to 0..N-1
        ci_node_total: ${{ fromJSON(inputs.node_total) }}
        # set N-1 indexes for parallel jobs
        # When you run 2 parallel jobs then first job will have index 0, the second job will have index 1 etc
        ci_node_index: ${{ fromJSON(inputs.node_index) }}
    env:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      CONFDIR: ${{ inputs.confdir }}
    steps:
      - id: setup
        name: Setup
        uses: notch8/actions/setup-env@v1.0.2
        with:
          tag: ${{ inputs.tag }}
          token: ${{ secrets.CHECKOUT_TOKEN || secrets.GITHUB_TOKEN }}
          subdir: ${{ inputs.subdir }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_step == 'test' }}
        with:
          limit-access-to-actor: true
      - name: Start containers
        run: >-
          cd ${{ inputs.subdir }};
          if [ -e node_modules ]; then rm -rf node_modules; fi;
          [ -f "db/schema.rb" ] && chmod 777 db/schema.rb;
          [ -f "bin/checkout_all.sh" ] && ./bin/checkout_all.sh;
          docker compose pull --ignore-pull-failures;
          docker compose up -d
      - name: Setup Solr
        if: ${{ inputs.solrTarget != '' }}
        shell: bash
        run: >-
          cd ${{ inputs.subdir }};
          docker compose exec -T solr sh -c
          "${{ inputs.setup_solr_cmd }}"
      - name: Setup db
        run: >-
          cd ${{ inputs.subdir }};
          docker compose exec -T web sh -c
          "${{ inputs.setup_db_cmd }}"
      - name: Run Specs
        id: run-specs
        env:
          # Specifies how many jobs you would like to run in parallel,
          # used for partitioning
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          # Use the index from matrix as an environment variable
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run: >-
          cd ${{ inputs.subdir }};
          docker compose exec -T web sh -c
          "${{ inputs.rspec_cmd }}"
      - name: Move Test Files
        if: always()
        env:
          # Specifies how many jobs you would like to run in parallel,
          # used for partitioning
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          # Use the index from matrix as an environment variable
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run: |
          if [ -f rspec.xml ]; then
            mv rspec.xml rspec-${CI_NODE_INDEX}.xml
          fi
      - id: after_care
        name: Upload Logs and Results
        uses: notch8/actions/after-care@hykuup-after-care
        if: always()
        with:
          reports: "rspec-*.xml"
